### ISSUE TITLE
uws 1.1: add ARCHIVED phase

### ISSUE THREAD

**Issue by kristinriebe** [aipescience/uws-client#22]
This phase is used when the service provider decides to keep the job metadata even after it was deleted or the destruction time of the job has passed. 
Jobs in ARCHIVED phase are not to be shown via the job list. They are only available when explicitely demanded using job list filtering: {service-url}/{jobs}?PHASE=ARCHIVED.
See section [2.2.1](http://www.ivoa.net/documents/UWS/20150626/PR-UWS-1.1-20150626.html#jobList) in the standard.

**Comment by adrpar** [comment]
starting this

**Comment by adrpar** [comment]
PR #23
